name: deploy-container

on:
  push:
    branches:
      - main
      - master
#     paths:
#       - 'react-micro-frontend/container/**'

defaults:
  run:
    working-directory: react-micro-frontend/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - name: Sanity Check
        run: ls -la
      - name: Sanity Check p2
        run: cd ./dist && ls -la && cd ..
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
#          SOURCE_DIR: "micro-frontend/react-micro-frontend/container/dist"
